### ISSUE TITLE
Bug: Not possible to scroll on "Choose your Campfire experience" screen

### ISSUE THREAD

**Issue by nrsimha** [firoorg/campfire#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently scrolling doesn't work so Continue button and some text is not visible on "Choose your Campfire" experience screen.

<img width="1332" alt="image" src="https://github.com/user-attachments/assets/ed3f4fc4-bc15-4f7e-801e-6c45602b622b">

### Expected Behavior

I would expect to be able to scroll screen to see hidden text and Continue button.

### Reproduce Steps

1) Install Campfire
2) Launch Campfire
3) Click on "Create new Campfire" button
4) If app window is smaller then "Choose your Campfire" screen hidden elements are not visible

### Environment

- Operating system and version:
Macos Ventura 13.4.1
- Device platform and version:
Not sure what that means
- Real device or emulator/simulator:
Macbook Air M1

**Comment by nrsimha** [comment]
Solution will be to wrap Column widget in SingleChildScrollView (or in SingleChildScrollView > Center > ConstrainedBox as create_or_restore_wallet_view uses)

https://github.com/firoorg/campfire/blob/d46d378424c6a2eb08df5f54836a5f0215249f76/lib/pages/add_wallet_views/add_wallet_view/add_wallet_view.dart#L185

https://github.com/firoorg/campfire/blob/d46d378424c6a2eb08df5f54836a5f0215249f76/lib/pages/add_wallet_views/create_or_restore_wallet_view/create_or_restore_wallet_view.dart#L48C3-L51C35

**Comment by justanwar** [comment]
Fixed in https://github.com/cypherstack/stack_wallet/commit/3b38dd6464068ea7d3b3d17fd3739bc0d9861a9a
