### ISSUE TITLE
Issue with campfire 

### ISSUE THREAD

**Issue by DavidKings33** [firoorg/campfire#3]
I was having issues with my campfire wallet yesterday and I contacted one of firo agent in the main group and he asked me to clearing electrumx cache and rescan Blockchain so I did that this morning after I was done with that I couldn't find my transaction history anymore, I couldn't find my firo balance anymore I just don't know what to do now

**Comment by justanwar** [comment]
Please try adding alternative Nodes. Connect to them, close the app fully, start the app again, clear electrumx cache and resync.

Electrumx02 should be the server closest to you, but you can try other servers as well.

Using mobile 4G connection might have the most issues. **Try with WiFi** as well if available. Also consider turning Tor on or off, or use VPN (if available).

The following nodes are available:
electrumx02.firo.org
electrumx01.firo.org
electrumx03.firo.org
electrumx.firo.org
(all port 50002)

**Comment by reubenyap** [comment]
Hi @DavidKings33 are u still having issues?

**Comment by DavidKings33** [comment]
> Hi @DavidKings33 are u still having issues?

No it's all good now
